core/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('money.urls'))
]


if settings.DEBUG:  # pragma: no cover
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG_TOOLBAR_INSTALLED:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

money/urls.py
from django.urls import path

from .views import accounts, operations, categories, operation_templates, import_web_bank, stats

urlpatterns = [
    path('', accounts.AccountIndexView.as_view(), name='homepage'),

    path('accounts', accounts.AccountIndexView.as_view(), name='accounts_index'),
    path('accounts/add', accounts.AccountAddView.as_view(), name='accounts_add'),
    path('accounts/view/<int:pk>', accounts.AccountDetailView.as_view(), name='accounts_view'),
    path(
        'accounts/view/<int:pk>/graphs',
        accounts.AccountGraphView.as_view(),
        name='accounts_graph'
    ),
    path(
        'accounts/view/<int:pk>/stats',
        accounts.AccountStatsView.as_view(),
        name='accounts_stats'
    ),
    path('accounts/edit/<int:pk>', accounts.AccountEditView.as_view(), name='accounts_edit'),
    path('accounts/delete/<int:pk>', accounts.AccountDeleteView.as_view(), name='accounts_delete'),
    path('accounts/csv/<int:pk>', accounts.AccountExportCsvView.as_view(), name='accounts_to_csv'),

    path(
        'accounts/<int:pk>/add_operation',
        operations.OperationAddView.as_view(),
        name='operations_add'
    ),
    path(
        'operations/view/<int:pk>',
        operations.OperationDetailView.as_view(),
        name='operations_view'
    ),
    path(
        'operations/edit/<int:pk>',
        operations.OperationEditView.as_view(),
        name='operations_edit'
    ),
    path(
        'operations/unlink/<int:pk>',
        operations.OperationUnlinkView.as_view(),
        name='operations_unlink'
    ),
    path(
        'operations/read/<int:pk>',
        operations.OperationSetReadView.as_view(),
        name='operations_read'
    ),
    path(
        'operations/set_pending/<int:pk>',
        operations.BankOperationSetPendingView.as_view(),
        name='operations_set_pending'
    ),
    path(
        'operations/delete/<int:pk>',
        operations.OperationDeleteView.as_view(),
        name='operations_delete'
    ),
    path(
        'operations/search',
        operations.OperationSearchView.as_view(),
        name="operations_search"
    ),
    path(
        'accounts/<int:pk>/mark_all_as_read',
        operations.OperationMarkAllReadView.as_view(),
        name='operations_mark_all_read'
    ),

    path(
        'import_web_bank/import_from_bank',
        import_web_bank.ImportFromBankView.as_view(),
        name="import_web_bank_import_from_bank"
    ),
    path(
        'import_web_bank/allow',
        import_web_bank.ImportWebBankAllowView.as_view(),
        name="import_web_bank_allow"
    ),
    path(
        'import_web_bank/imported_accounts',
        import_web_bank.ImportWebBankAjaxImportedAccountsView.as_view(),
        name="import_web_bank_imported_accounts"
    ),
    path(
        'import_web_bank/delete/<int:account_pk>',
        import_web_bank.ImportWebBankDeleteImportedAccountView.as_view(),
        name='import_web_bank_delete_imported_account'
    ),
    path(
        'import_web_bank/delete_all',
        import_web_bank.ImportWebBankDeleteAllImportedAccountsView.as_view(),
        name='import_web_bank_delete_all_imported_accounts'
    ),

    path('categories', categories.CategoryIndexView.as_view(), name='categories_index'),
    path('categories/add', categories.CategoryAddView.as_view(), name='categories_add'),
    path(
        'categories/view/<int:pk>',
        categories.CategoryDetailView.as_view(),
        name='categories_view'
    ),
    path('categories/edit/<int:pk>', categories.CategoryEditView.as_view(), name='categories_edit'),
    path(
        'categories/delete/<int:pk>',
        categories.CategoryDeleteView.as_view(),
        name='categories_delete'
    ),
    path(
        'categories/get_auto_affect',
        categories.CategoryGetAutoAffectView.as_view(),
        name='categories_get_auto_affect'
    ),

    path(
        'operation_templates',
        operation_templates.OperationTemplateIndexView.as_view(),
        name='operation_templates_index'
    ),
    path(
        'operation_templates/add',
        operation_templates.OperationTemplateAddView.as_view(),
        name='operation_templates_add'
    ),
    path(
        'operation_templates/edit/<int:pk>',
        operation_templates.OperationTemplateEditView.as_view(),
        name='operation_templates_edit'
    ),
    path(
        'operation_templates/delete/<int:pk>',
        operation_templates.OperationTemplateDeleteView.as_view(),
        name='operation_templates_delete'
    ),

    path('stats', stats.StatsView.as_view(), name="stats")
]

money/models/import_authorization.py
from django.db import models
import datetime


class ImportAuthorization(models.Model):
    key = models.CharField(max_length=65)
    date = models.DateTimeField(default=datetime.datetime.now)

money/models/operation_templates.py
from django.db import models
from django.db.models import Q

from money.models.accounts import Account
from money.models.categories import Category


class OperationTemplate(models.Model):
    title = models.CharField(max_length=255)
    amount = models.FloatField(default=None, null=True, blank=True)
    description = models.CharField(max_length=255, blank=True, default=None, null=True)
    comment = models.TextField(blank=True, default=None, null=True)
    method = models.CharField(max_length=50, blank=True, default=None, null=True)
    accounts = models.ManyToManyField(Account)
    categories = models.ManyToManyField(Category, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title'], name='unique_name'),
            models.CheckConstraint(
                check=(
                    ~Q(amount=None)
                    | ~Q(description=None)
                    | ~Q(comment="")
                    | ~Q(method=None)
                ),
                name="must_provide_data"
            )
        ]

    def __str__(self):
        return "Operation template: " + self.title

money/models/operations.py
from django.db import models
from django.db.models import Q, F
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver
import datetime

from money.models.accounts import Account
from money.models.categories import Category


class Operation(models.Model):
    class BankOperationImportMethod(models.IntegerChoices):
        WEB = 1
        CSV = 2

    _date_paid = models.DateField(db_column="date_paid", default=datetime.date.today)
    _bank_date = models.DateField(null=True, db_column="bank_date")
    import_datetime = models.DateTimeField(null=True, blank=True)
    _amount = models.FloatField(db_column="amount")
    description = models.CharField(max_length=255, blank=True, default="")
    bank_description = models.CharField(max_length=255, blank=True, default="")
    comment = models.TextField(blank=True)
    bank_comment = models.TextField(blank=True)
    read = models.BooleanField(default=False)
    method = models.CharField(max_length=50)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, blank=True)
    bank_import_method = models.IntegerField(
        choices=BankOperationImportMethod.choices,
        null=True,
        default=None
    )
    linked_operations = models.ManyToManyField("self", blank=True)
    takes_from_support = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.CheckConstraint(check=~Q(_amount=0), name="operation_not_zero"),
            models.CheckConstraint(
                check=Q(_bank_date=None) | Q(_date_paid__lte=F('_bank_date')),
                name="date_paid_before_acted"
            ),
            models.CheckConstraint(
                check=(
                    Q(_bank_date=None) & Q(bank_import_method=None))
                | (~Q(_bank_date=None) & ~Q(bank_import_method=None)),
                name="bank_operation_has_import_method"
            ),
            models.CheckConstraint(
                check=(~Q(_bank_date=None) | Q(takes_from_support=False)),
                name="only_bank_operations_take_from_support"
            ),
        ]

    @property
    def date_paid(self):
        return self._date_paid

    @date_paid.setter
    def date_paid(self, value):
        if isinstance(value, str):
            value = datetime.date.fromisoformat(value)
        elif not isinstance(value, datetime.date):
            value = datetime.date(value)

        self._date_paid = value

    @property
    def bank_date(self):
        return self._bank_date

    @bank_date.setter
    def bank_date(self, value):
        if isinstance(value, str):
            value = datetime.date.fromisoformat(value)
        elif not isinstance(value, datetime.date):
            value = datetime.date(value)

        self._bank_date = value

        if self.bank_import_method is None:
            # By default, setting bank_date define import_method, mostly to ease tests
            # unless other method was already specified
            self.bank_import_method = self.BankOperationImportMethod.WEB

    @property
    def amount(self):
        return self._amount

    @amount.setter
    def amount(self, value):
        if not isinstance(value, float):
            value = float(value)

        self._amount = value

    @property
    def is_bank_operation(self):
        return (self._bank_date is not None)

    @property
    def is_merged_with_pending(self):
        return (len(self.description) != 0 and len(self.bank_description) != 0)

    @property
    def all_categories(self):
        if len(self.categories.all()) > 0:
            return self.categories.all()
        else:
            return [Category.without_category()]

    def clean_fields(self, exclude=None):
        if (exclude is None or 'amount' not in exclude) and self.amount == 0.:
            raise ValidationError({'amount': _("Amount cannot be zero.")})

        if self.bank_date is not None and self.date_paid > self.bank_date:
            raise ValidationError({"bank_date": _("Paid date must be before acted date.")})

        description_len = 0
        if self.description is not None:
            description_len = len(self.description)

        bank_description_len = 0
        if self.bank_description is not None:
            bank_description_len = len(self.bank_description)

        if description_len == 0 and bank_description_len == 0:
            raise ValidationError(_("Either description or bank description must be provided."))

        return super().clean_fields(exclude)

    def __str__(self):
        string = ""

        if self.date_paid is not None:
            string = str(self.date_paid) + ": "

        if hasattr(self, 'account'):
            string += self.account.title + " - "

        if self.method != "":
            string += self.method + " - "

        if self.description != "":
            string += self.description
        else:
            string += self.bank_description

        if self.amount is not None:
            string += " | " + format(self.amount, '.2f') + "€"

        if string == "" or string == str(datetime.date.today()) + ": ":
            string = "Empty Operation"

        return string

    def is_same_as(self, other):
        if not isinstance(other, Operation):
            return False

        # Comparing descriptions and coments sometime are not accurate, especially when
        # comparing imported bank operations from csv and imported bank operations from
        # web.

        compared_fields = ['_bank_date', '_amount']

        if self.bank_import_method == other.bank_import_method:
            compared_fields += ['bank_description']

        for field in compared_fields:
            if isinstance(vars(self)[field], str):
                # CANE web bank evolved and descriptions became uppercase...:
                if vars(self)[field].lower() != vars(other)[field].lower():
                    return False
            else:
                if vars(self)[field] != vars(other)[field]:
                    return False

        return True

    @property
    def transfer_opposite_operation(self):
        """
        If the operation is a transfer to another account, this property
        returns the operation at the other side of the transfer.
        """
        for o in self.linked_operations.all():
            if (o.account != self.account
                    and o.amount == -self.amount
                    and o.bank_date == self.bank_date):
                return o

        return None

    def toCsvRow(self):
        categories = ", ".join([c.title for c in self.categories.all()])

        return [
            self._bank_date.strftime("%d/%m/%Y"),
            self._date_paid.strftime("%d/%m/%Y"),
            self.method,
            self.bank_description,
            self.bank_comment,
            self.description,
            self.comment,
            str(self.amount),
            categories
        ]


class OperationReceipt(models.Model):
    class OperationReceiptType(models.IntegerChoices):
        OTHER = 0, _('Other')
        BILL = 1, _('Bill')
        RECEIPT = 2, _('Receipt')
        QUOTE = 3, _('Quote')
        WARRANTY = 4, _('Warranty')

    operation = models.ForeignKey(Operation, on_delete=models.CASCADE)
    receipt_file = models.FileField(upload_to='uploads')
    filename = models.CharField(max_length=255)
    kind = models.IntegerField(
        choices=OperationReceiptType.choices,
        default=OperationReceiptType.OTHER
    )

    def __str__(self):
        return str(self.operation) + " | " + self.filename + " | " + str(self.get_kind_display())


@receiver(models.signals.post_delete, sender=OperationReceipt)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    instance.receipt_file.delete(save=False)


@receiver(models.signals.pre_save, sender=OperationReceipt)
def auto_delete_old_file_on_update(sender, instance, **kwargs):
    instance.filename = instance.receipt_file.name

    if instance.pk:
        old_operation_receipt = OperationReceipt.objects.get(pk=instance.pk)
        if old_operation_receipt.receipt_file.name != instance.receipt_file.name:
            old_operation_receipt.receipt_file.delete(save=False)

money/views/operation_templates.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from money.models.operation_templates import OperationTemplate
from money.models.operations import Operation
from money.forms.operation_templates import OperationTemplateForm
from money.utils import operation_templates as utils


class OperationTemplateIndexView(ListView):
    template_name = 'operation_templates/index.html'
    context_object_name = 'operation_templates'
    queryset = OperationTemplate.objects.all().order_by('title').prefetch_related(
        'categories', 'accounts'
    )


class OperationTemplateAddView(CreateView):
    model = OperationTemplate
    template_name = 'operation_templates/add.html'
    form_class = OperationTemplateForm
    success_url = reverse_lazy('operation_templates_index')

    def get_initial(self):
        initial = super().get_initial()
        operation_pk = self.request.GET.get('operation', None)

        if operation_pk is not None and operation_pk.isdigit():
            operation = Operation.objects.filter(pk=operation_pk).prefetch_related(
                'categories', 'account'
            ).first()

            if operation is not None:
                initial = {**initial, **utils.get_init_values(operation)}

        return initial


class OperationTemplateEditView(UpdateView):
    model = OperationTemplate
    template_name = 'operation_templates/edit.html'
    form_class = OperationTemplateForm
    success_url = reverse_lazy('operation_templates_index')


class OperationTemplateDeleteView(DeleteView):
    model = OperationTemplate
    template_name = None
    http_method_names = ["delete", "post"]
    success_url = reverse_lazy('operation_templates_index')

money/views/stats.py
from django.views.generic.base import TemplateView

from money.mixins import SelectMonthMixin
from money.utils import graphs, stats


class StatsView(SelectMonthMixin, TemplateView):
    template_name = 'stats/stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['graph_monthly_balance'] = graphs.get_all_accounts_monthly_balances(
            self.end_asked_month
        )[-24:]

        context['graph_yearly_balance'] = graphs.get_all_accounts_yearly_balances(
            self.end_asked_month
        )[-24:]

        context['month_repartition'] = stats.get_categories_repartition_by_months(
            None, self.end_asked_month
        )
        context['year_repartition'] = stats.get_categories_repartition_by_years(
            None, self.asked_date.year+1
        )

        return context

money/templates/operations/_button_clone.html
{% load i18n %}

<button
    class="btn btn-sm btn-warning open-select-dest-account-modal"
    title="{% trans 'Clone' %}"
    data-modal-title="{% trans 'Clone an operation' %}"
    data-modal-text="{% trans 'Select in which account you want to copy the operation:' %}"
    data-action="duplicate"
    data-operation="{{ operation.pk }}"
>
    <i class="far fa-clone"></i>
</button>

money/templates/operations/_button_refund.html
{% load i18n %}

<button
    class="btn btn-sm btn-warning open-select-dest-account-modal"
    title="{% trans 'Refund this operation' %}"
    data-modal-title="{% trans 'Refund an operation' %}"
    data-modal-text="{% trans 'Select in which account the refunded operation will appear:' %}"
    data-action="refund"
    data-operation="{{ operation.pk }}"
>
    <i class="fas fa-undo-alt"></i>
</button>

money/templates/operations/_buttons.html
{% load i18n %}

<a class="btn btn-info btn-sm" href="{% url 'operations_view' operation.id %}" title="{% trans 'Show' %}" role="button">
    <i class="fas fa-eye"></i>
</a>
<a class="btn btn-sm btn-warning" href="{% url 'operations_edit' operation.id %}" title="{% trans 'Edit' %}" role="button">
    <i class="fas fa-pen"></i>
</a>
{% include "operations/_button_clone.html" %}
{% include "operations/_button_refund.html" %}
<a class="btn btn-sm btn-warning" href="{% url 'operation_templates_add' %}?operation={{ operation.pk }}" title="{% trans 'Create template from this operation' %}" role="button">
    <i class="fa fa-ruler-combined"></i>
</a>

money/templates/operations/_form.html
{% load i18n %}
{% load crispy_forms_tags %}

<form method="post" action="" class="form-horizontal" enctype="multipart/form-data">

    {% if form_dates %}
    <div class="form-group row" id="dates_fieldset">
        <label class="col-lg-2">{% trans "Paid dates" %}</label>
        <div class="col-8">
            {% crispy form_dates form_dates.form.helper %}

            <div class="col-2 dates-formset-add-button text-center"></div>
        </div>
    </div>
    {% endif %}

    {% crispy form %}

    <div class="form-group row" id="receipts_fieldset">
        <label class="col-lg-2">
            {% trans "Receipts" %}
            {% if form_dates %}
            <small class="form-text text-muted">
                <i class="fa fa-info-circle"></i>
                {% trans "If you set many paid dates, receipts will be bound only to the first operation." %}
            </small>
            {% endif %}
        </label>
        <div class="col-8">
            {% crispy form_receipts form_receipts.form.helper %}

            <div class="offset-5 receipts-formset-add-button"></div>
        </div>
    </div>

    <input type="submit" name="save" value="Save" class="btn btn-primary btn-default offset-lg-2" id="submit-id-save">
</form>

money/templates/operations/_list.html
{% load i18n %}
{% load money_paginator %}
{% load list_prev %}
{% load display_amount %}

<table class="table table-bordered table-sm table-hover">
    <thead class="sticky-top thead-light">
        <tr>
            <th colspan="{% if display_account_colum %}8{% else %}7{% endif %}">
                {% display_pagination hashtag=hashtag %}
            </th>
        </tr>
        <tr>
            <th scope="col">
                {% trans "Acted Date (bank date)" %}
                <i class="fa fa-sort-amount-up"></i>
            </th>
            <th scope="col">{% trans "Paid Date" %}</th>
            {% if display_account_colum %}
                <th scope="col">{% trans "Account" %}</th>
            {% endif %}
            <th scope="col">{% trans "Method" %}</th>
            <th scope="col">{% trans "Description" %}</th>
            <th scope="col">{% trans "Categories" %}</th>
            <th scope="col">{% trans "Amount" %}</th>
            <th scope="col">{% trans "Actions" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for operation in operations %}
        {% with previous_operation=operations|previous:forloop.counter0 %}
        {% if previous_operation is not None and previous_operation.bank_date|date:"Ym" != operation.bank_date|date:"Ym" %}
            <tr>
                <td colspan="{% if display_account_colum %}8{% else %}7{% endif %}" class="table-info text-center">
                    <i class="fas fa-angle-down"></i>
                    {{ operation.bank_date|date:"F Y" }}
                </td>
            </tr>
        {% endif %}
        {% if asked_date is not None and previous_operation is not None and operation.bank_date < asked_date and previous_operation.bank_date > asked_date %}
            <tr class="table-success">
                <td colspan="7"><b>{{ asked_date|date:"d/m/Y" }}</b></td>
            </tr>
        {% endif %}
        {% endwith %}
        {% if operation.pk in hidden_operations %}
        <tr
            class="
            {% if asked_date is not None and asked_date == operation.bank_date %}
                table-success
            {% elif not operation.read %}
                table-secondary
            {% endif %}
            {% if operation.pk in hidden_operations %}
                hidden-operation
            {% endif %}
            "
        >
            <td colspan="7" class="text-center">
                <button class="btn btn-outline-secondary btn-sm show-operation-btn" title="{% trans 'Display the operation' %}" ><i class="fa fa-eye-slash"></i></button>
            </td>
        </tr>
        {% endif %}
        <tr
            {% if asked_date is not None and asked_date == operation.bank_date or not operation.read or operation.pk in hidden_operations %}
                class="
                {% if asked_date is not None and asked_date == operation.bank_date %}
                    table-success
                {% elif not operation.read %}
                    table-secondary
                {% endif %}
                "
            {% endif %}
        >
            <td>
                {% if asked_date is not None and asked_date == operation.bank_date %}<b>{% endif %}
                    <a href="{% url 'accounts_view' operation.account.id %}?date={{ operation.bank_date|date:'Y-m-d'}}#tab_tables">
                        {{ operation.bank_date|date:"d/m/Y" }}
                    </a>
                {% if asked_date is not None and asked_date == operation.bank_date %}</b>{% endif %}
            </td>
            <td>{{ operation.date_paid|date:"d/m/Y" }}</td>
            {% if display_account_colum %}
                <td>
                    <a href="{% url 'accounts_view' operation.account.id %}">{{ operation.account.title }}</a>
                </td>
            {% endif %}
            <td>
                {{ operation.method }}
                {% if operation.transfer_opposite_operation is not None %}
                    <a href="{% url 'operations_view' operation.transfer_opposite_operation.id %}" class="badge badge-secondary">
                        <i class="fas fa-exchange-alt" data-toggle="tooltip" data-placement="top" title="{% if operation.amount > 0 %}{% trans "Tranfer from" %}{% else %}{% trans "Transfer to" %}{% endif %} {{ operation.transfer_opposite_operation.account.title }}"></i>
                    </a>
                {% endif %}
            </td>
            <td>
                {% if operation.linked_operations.all|length or operation.operationreceipt_set.all|length %}
                    <span class="float-right">
                    {% if operation.linked_operations.all|length %}
                        <i class="fa fa-code-branch"></i>
                    {% endif %}
                    {% if operation.operationreceipt_set.all|length %}
                        <i class="far fa-file"></i>
                    {% endif %}
                    </span>
                {% endif %}
                {% if operation.description|length %}
                    {{ operation.description }}
                    {% if operation.bank_description is not None and operation.bank_description|length %}
                        <span
                            class="badge badge-secondary"
                            data-toggle="popover-hover"
                            title="{{ operation.bank_description }}"
                            data-content="{% if operation.bank_comment|length %}{{ operation.bank_comment }}{% else %}{% trans 'No bank description' %}{% endif %}"
                        >
                            <i class="fas fa-landmark"></i>
                        </span>
                    {% endif %}
                    {% if operation.comment|length %}
                        <br>
                        <small>{{ operation.comment|linebreaksbr }}</small>
                    {% endif %}
                {% else %}
                    <samp>
                        {{ operation.bank_description }}
                        {% if operation.bank_comment is not None and operation.bank_comment|length %}
                            <br>
                            <small>{{ operation.bank_comment|linebreaksbr }}</small>
                        {% endif %}
                    </samp>
                {% endif %}
            </td>
            <td>
                {% include "categories/_list_badges.html" with categories=operation.all_categories %}
            </td>
            <td class="text-right">
                {% if operation.takes_from_support %}
                    <i class="fa-solid fa-share-from-square" data-toggle="tooltip" data-placement="top" title="Taken from the support"></i>
                {% endif %}
                {% display_amount operation.amount %}
            </td>
            <td>
                {% if operation.is_merged_with_pending %}
                <form data-text="{% trans 'Unlink ?' %}" data-modal="confirm" id="unlink-form-{{ operation.id }}" action="{% url 'operations_unlink' operation.id %}" method="post">
                    {% csrf_token %}
                </form>
                {% endif %}
                {% if not operation.read %}
                <form id="read-form-{{ operation.id }}" action="{% url 'operations_read' operation.id %}" method="post">
                    {% csrf_token %}
                </form>
                {% endif %}
                <div class="btn-group" role="group">
                    {% include "operations/_buttons.html" %}
                    {% if operation.is_merged_with_pending %}
                    <button type="submit" form="unlink-form-{{ operation.id }}" title="{% trans 'Unlink the operation' %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-unlink"></i>
                    </button>
                    {% else %}
                    <a class="btn btn-primary btn-sm" href="{% url 'operations_set_pending' operation.id %}" title="{% trans 'Select the matching pending operation' %}" role="button">
                        <i class="fas fa-link"></i>
                    </a>
                    {% endif %}
                    {% if not operation.read %}
                    <button type="submit" form="read-form-{{ operation.id }}" title="{% trans 'Mark as read' %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-check"></i>
                    </button>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    {% if sum_amount is not None and operations|length > 1 %}
        <tfoot>
            <tr>
                <th colspan="{% if display_account_colum %}6{% else %}5{% endif %}" class="text-right">Σ</th>
                <th class="text-right">
                    {% display_amount sum_amount %}
                </th>
                <th></th>
            </tr>
        </tfoot>
    {% endif %}
</table>

money/templates/operations/_modal_select_dest_account.html
{% load i18n %}

<div id="modal-select-dest-account" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
                <div class="list-group">
                    {% for account in dest_accounts_clone_operation %}
                    <a data-base-href="{% url 'operations_add' account.id %}" href="#" class="list-group-item list-group-item-action">{{ account.title }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel" %}</button>
            </div>
        </div>
    </div>
</div>

money/templates/operations/add.html
{% extends "base.html" %}

{% load i18n %}

{% block breadcumb %}
{{ block.super }}

<li class="breadcrumb-item"><a href="{% url 'accounts_index' %}">{% trans "Accounts" %}</a></li>
<li class="breadcrumb-item"><a href="{% url 'accounts_view' account.id %}">{{ account.title }}</a></li>
<li class="breadcrumb-item active">{% trans "Add an operation" %}</li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm">
        <h1>{% trans "Add an operation" %}</h1>
    </div>
</div>

{% include "operations/_form.html" %}

{% endblock %}



{% block scripts %}
{{ block.super }}
<script>
$(function () {
    $("#id_description").on('blur', function(e) {
        if ($('#id_categories').val().length == 0) {
            var desc = encodeURIComponent($(this).val());

            $.getJSON("{% url 'categories_get_auto_affect' %}?desc=" + desc, function(result) {
                $("#id_categories").val(result);
                $("#id_categories").trigger("change");
            });
        }
    });
});
</script>
{% endblock %}