core/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('money.urls'))
]


if settings.DEBUG:  # pragma: no cover
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG_TOOLBAR_INSTALLED:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

money/urls.py
from django.urls import path

from .views import accounts, operations, categories, operation_templates, import_web_bank, stats

urlpatterns = [
    path('', accounts.AccountIndexView.as_view(), name='homepage'),

    path('accounts', accounts.AccountIndexView.as_view(), name='accounts_index'),
    path('accounts/add', accounts.AccountAddView.as_view(), name='accounts_add'),
    path('accounts/view/<int:pk>', accounts.AccountDetailView.as_view(), name='accounts_view'),
    path(
        'accounts/view/<int:pk>/graphs',
        accounts.AccountGraphView.as_view(),
        name='accounts_graph'
    ),
    path(
        'accounts/view/<int:pk>/stats',
        accounts.AccountStatsView.as_view(),
        name='accounts_stats'
    ),
    path('accounts/edit/<int:pk>', accounts.AccountEditView.as_view(), name='accounts_edit'),
    path('accounts/delete/<int:pk>', accounts.AccountDeleteView.as_view(), name='accounts_delete'),
    path('accounts/csv/<int:pk>', accounts.AccountExportCsvView.as_view(), name='accounts_to_csv'),

    path(
        'accounts/<int:pk>/add_operation',
        operations.OperationAddView.as_view(),
        name='operations_add'
    ),
    path(
        'operations/view/<int:pk>',
        operations.OperationDetailView.as_view(),
        name='operations_view'
    ),
    path(
        'operations/edit/<int:pk>',
        operations.OperationEditView.as_view(),
        name='operations_edit'
    ),
    path(
        'operations/unlink/<int:pk>',
        operations.OperationUnlinkView.as_view(),
        name='operations_unlink'
    ),
    path(
        'operations/read/<int:pk>',
        operations.OperationSetReadView.as_view(),
        name='operations_read'
    ),
    path(
        'operations/set_pending/<int:pk>',
        operations.BankOperationSetPendingView.as_view(),
        name='operations_set_pending'
    ),
    path(
        'operations/delete/<int:pk>',
        operations.OperationDeleteView.as_view(),
        name='operations_delete'
    ),
    path(
        'operations/search',
        operations.OperationSearchView.as_view(),
        name="operations_search"
    ),
    path(
        'accounts/<int:pk>/mark_all_as_read',
        operations.OperationMarkAllReadView.as_view(),
        name='operations_mark_all_read'
    ),

    path(
        'import_web_bank/import_from_bank',
        import_web_bank.ImportFromBankView.as_view(),
        name="import_web_bank_import_from_bank"
    ),
    path(
        'import_web_bank/allow',
        import_web_bank.ImportWebBankAllowView.as_view(),
        name="import_web_bank_allow"
    ),
    path(
        'import_web_bank/imported_accounts',
        import_web_bank.ImportWebBankAjaxImportedAccountsView.as_view(),
        name="import_web_bank_imported_accounts"
    ),
    path(
        'import_web_bank/delete/<int:account_pk>',
        import_web_bank.ImportWebBankDeleteImportedAccountView.as_view(),
        name='import_web_bank_delete_imported_account'
    ),
    path(
        'import_web_bank/delete_all',
        import_web_bank.ImportWebBankDeleteAllImportedAccountsView.as_view(),
        name='import_web_bank_delete_all_imported_accounts'
    ),

    path('categories', categories.CategoryIndexView.as_view(), name='categories_index'),
    path('categories/add', categories.CategoryAddView.as_view(), name='categories_add'),
    path(
        'categories/view/<int:pk>',
        categories.CategoryDetailView.as_view(),
        name='categories_view'
    ),
    path('categories/edit/<int:pk>', categories.CategoryEditView.as_view(), name='categories_edit'),
    path(
        'categories/delete/<int:pk>',
        categories.CategoryDeleteView.as_view(),
        name='categories_delete'
    ),
    path(
        'categories/get_auto_affect',
        categories.CategoryGetAutoAffectView.as_view(),
        name='categories_get_auto_affect'
    ),

    path(
        'operation_templates',
        operation_templates.OperationTemplateIndexView.as_view(),
        name='operation_templates_index'
    ),
    path(
        'operation_templates/add',
        operation_templates.OperationTemplateAddView.as_view(),
        name='operation_templates_add'
    ),
    path(
        'operation_templates/edit/<int:pk>',
        operation_templates.OperationTemplateEditView.as_view(),
        name='operation_templates_edit'
    ),
    path(
        'operation_templates/delete/<int:pk>',
        operation_templates.OperationTemplateDeleteView.as_view(),
        name='operation_templates_delete'
    ),

    path('stats', stats.StatsView.as_view(), name="stats")
]

money/models/accounts.py
from django.db import models
from django.db.models import Q
from django.core.validators import MinValueValidator


class Account(models.Model):
    title = models.CharField(max_length=100)
    number = models.BigIntegerField(unique=True)
    balance = models.FloatField(default=None, blank=True, null=True)
    balance_date = models.DateField(default=None, blank=True, null=True)
    no_pendings = models.BooleanField(default=False)
    balance_limit = models.FloatField(default=None, blank=True, null=True, validators=[
        MinValueValidator(0.01)
    ])
    initial_amount = models.FloatField(default=0.00, blank=True, null=False, validators=[
        MinValueValidator(0.00)
    ])
    support_amount = models.FloatField(default=None, blank=True, null=True)
    comment = models.TextField(blank=True)
    bank_local_balances_can_be_different = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(balance_limit=None) | Q(balance_limit__gt=0),
                name="account_balance_limit_positive"
            ),
            models.CheckConstraint(
                check=Q(support_amount=None) | Q(support_amount__gt=0),
                name="account_support_amount"
            ),
        ]

    def __str__(self):
        return self.title + " (" + str(self.number) + ")"

money/models/operation_templates.py
from django.db import models
from django.db.models import Q

from money.models.accounts import Account
from money.models.categories import Category


class OperationTemplate(models.Model):
    title = models.CharField(max_length=255)
    amount = models.FloatField(default=None, null=True, blank=True)
    description = models.CharField(max_length=255, blank=True, default=None, null=True)
    comment = models.TextField(blank=True, default=None, null=True)
    method = models.CharField(max_length=50, blank=True, default=None, null=True)
    accounts = models.ManyToManyField(Account)
    categories = models.ManyToManyField(Category, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title'], name='unique_name'),
            models.CheckConstraint(
                check=(
                    ~Q(amount=None)
                    | ~Q(description=None)
                    | ~Q(comment="")
                    | ~Q(method=None)
                ),
                name="must_provide_data"
            )
        ]

    def __str__(self):
        return "Operation template: " + self.title

money/views/accounts.py
import datetime
import traceback
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from django.conf import settings
from django.db.models import Q, Sum, F, Count
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.files.uploadhandler import TemporaryFileUploadHandler
from django.utils.decorators import method_decorator
from django.db import transaction
from django.shortcuts import redirect

from money.models.accounts import Account
from money.models.operations import Operation
from money.forms.accounts import AccountForm
from money.mixins import SelectMonthMixin, ListDestAccountsToCloneOperationMixin
from money.utils.import_data import ImportCsvOperations, ImportCsvBankOperations
from money.utils import graphs, operations, stats


class AccountIndexView(ListView):
    template_name = 'accounts/index.html'
    context_object_name = 'accounts'
    queryset = Account.objects.all().annotate(
        occupancy=100*F('balance') / F('balance_limit'),
        nb_not_read=Count(
            'operation',
            filter=Q(operation__read=False) & ~Q(operation___bank_date=None)
        ),
        nb_pendings=Count('operation', filter=Q(operation___bank_date=None))
    ).order_by('title')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['sum_accounts'] = sum(
            [a.balance for a in context['object_list'] if a.balance is not None]
        )

        return context


class AccountDetailView(SingleObjectMixin, ListView, ListDestAccountsToCloneOperationMixin):
    model = Account
    template_name = 'accounts/detail.html'
    object = None
    paginate_by = settings.MONEY['paginate_by']
    asked_date = None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Account.objects.all().annotate(
            occupancy=100*F('balance') / F('balance_limit')
        ))

        date = request.GET.get('date', None)
        current_page = int(request.GET.get('page', 1))

        if date is not None:
            self.asked_date = datetime.date.fromisoformat(date)
            target_page = operations.get_page_containing_date(self.object, self.asked_date)

            if current_page != target_page:
                url_params = "?page=" + str(target_page) + "&date=" + str(self.asked_date)
                return redirect(
                    reverse_lazy('accounts_view', kwargs={'pk': self.object.pk}) + url_params
                )

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['hidden_operations'] = operations.hidden_operations(
            context['object_list'], self.object
        )

        context['asked_date'] = self.asked_date

        context['nb_not_read'] = Operation.objects.filter(
            Q(account=self.object) & ~Q(_bank_date=None) & Q(read=False)
        ).count()

        context['local_balance_without_pending'] = Operation.objects.filter(
            Q(account=self.object) & ~Q(_bank_date=None)
        ).aggregate(Sum('_amount'))['_amount__sum']

        if context['local_balance_without_pending'] is not None:
            context['local_balance_without_pending'] = round(
                context['local_balance_without_pending'] + self.object.initial_amount, 2
            )

            if self.object.balance is not None:
                context['diff_bank_local_balance'] = abs(
                    self.object.balance - context['local_balance_without_pending']
                )

        if not self.object.no_pendings:
            context['pending_operations'] = Operation.objects.filter(
                Q(account=self.object) & Q(_bank_date=None)
            ).select_related('account').order_by('-_date_paid').prefetch_related(
                'categories',
                'operationreceipt_set',
                'linked_operations',
                'linked_operations__account'
            )

            context['pending_balance'] = Operation.objects.filter(
                Q(account=self.object) & Q(_bank_date=None)
            ).aggregate(Sum('_amount'))['_amount__sum'] or 0.

            context['local_balance_with_pending'] = context['pending_balance']
            if context['local_balance_without_pending'] is not None:
                context['local_balance_with_pending'] += context['local_balance_without_pending']

            date_boundary = datetime.date.today() + datetime.timedelta(
                days=settings.MONEY['hidden_pending_operations_time_boundary']
            )
            context['hidden_pending_operations'] = Operation.objects.filter(
                Q(account=self.object) & Q(_bank_date=None) & Q(_date_paid__gte=date_boundary)
            )

        if self.object.support_amount:
            context['total_from_support_amount'] = Operation.objects.filter(
                Q(account=self.object) & ~Q(_bank_date=None) & Q(takes_from_support=True)
            ).aggregate(Sum('_amount'))['_amount__sum'] or 0.

            context['current_support_amount'] = round(
                self.object.support_amount - context['total_from_support_amount'], 2
            )

        return context

    def get_queryset(self, *args, **kwargs):
        return Operation.objects.filter(
                Q(account=self.object) & ~Q(_bank_date=None)
        ).select_related('account').order_by(
            '-_bank_date', '-import_datetime', '-_date_paid'
        ).prefetch_related(
            'categories', 'operationreceipt_set', 'linked_operations', 'linked_operations__account'
        )


class AccountGraphView(SelectMonthMixin, DetailView):
    model = Account
    template_name = 'accounts/graphs.html'
    object = None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Account.objects.all())

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        graph_monthly_balance, display_balance_limit = graphs.get_account_monthly_balances(
            self.object, self.end_asked_month
        )
        context['graph_monthly_balance'] = graph_monthly_balance[-24:]
        context['display_balance_limit'] = display_balance_limit

        context['graph_expense_categories'] = graphs.get_account_categories_expenses_repartition(
            self.object, self.begin_asked_month, self.end_asked_month
        )
        context['expense_categories_total'] = sum(
            [r['balance'] for r in context['graph_expense_categories']]
        )
        context['graph_income_categories'] = graphs.get_account_categories_incomes_repartition(
            self.object, self.begin_asked_month, self.end_asked_month
        )
        context['income_categories_total'] = sum(
            [r['balance'] for r in context['graph_income_categories']]
        )

        context['categories_repartition'] = graphs.get_account_categories_repartition(self.object)
        context['graph_categories_repartition'] = [
            e for e in context['categories_repartition'] if e['balance'] > 0
        ]

        return context


class AccountStatsView(SelectMonthMixin, DetailView):
    model = Account
    template_name = 'accounts/stats.html'
    object = None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Account.objects.all())

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['month_repartition'] = stats.get_categories_repartition_by_months(
            self.object, self.end_asked_month
        )
        context['year_repartition'] = stats.get_categories_repartition_by_years(
            self.object, self.asked_date.year+1
        )

        return context


@method_decorator(csrf_exempt, 'dispatch')
class AccountAddView(CreateView):
    model = Account
    template_name = 'accounts/add.html'
    form_class = AccountForm
    object = None

    def post(self, request, *args, **kwargs):
        request.upload_handlers = [TemporaryFileUploadHandler(request)]
        return self._post(request, *args, **kwargs)

    @method_decorator(csrf_protect)
    def _post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        try:
            with transaction.atomic():
                self.object = form.save()

                if 'csvOperations' in form.files and not self.object.no_pendings:
                    try:
                        importCsvOperations = ImportCsvOperations(
                            form.files['csvOperations'].temporary_file_path(),
                            self.object
                        )
                        importCsvOperations.process()
                    except Exception as e:
                        traceback.print_exc()
                        raise Exception("csvOperations", str(e))

                if 'csvBankOperations' in form.files:
                    try:
                        importCSvBankOperations = ImportCsvBankOperations(
                            form.files['csvBankOperations'].temporary_file_path(),
                            self.object
                        )
                        importCSvBankOperations.process()
                    except Exception as e:
                        traceback.print_exc()
                        raise Exception("csvBankOperations", str(e))
        except Exception as e:
            field, msg = e.args
            form.add_error(field, msg)
            return super().form_invalid(form)

        return redirect(self.get_success_url())

    def get_success_url(self):

money/templates/accounts/_tables.html
{% load i18n %}
{% load humanize %}

{% if not account.no_pendings %}
<div class="row">
    <div class="col-sm">
        <h2><span class="badge badge-info">{{ pending_operations|length }}</span> {% trans "Pending operations" %}</h2>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        {% include "operations/_pending_list.html" %}
    </div>
</div>
{% endif %}


<div class="row">
    <div class="col-sm">
        <div class="row justify-content-between align-items-center">
            <div class="col-auto mr-auto">
                <h2>{% trans "Acted operations" %}</h2>
            </div>
            <div class="col-auto">
                {% if nb_not_read > 0 %}
                    <form id="mark_all_read_form" action="{% url "operations_mark_all_read" account.id %}" method="post" class="form-inline">
                        {% csrf_token %}
                    </form>
                {% endif %}
                <form method="get" class="form-inline">
                    <div class="input-group">
                        <input name="date" required type="text" class="datepicker form-control form-control-sm mb-2" placeholder="{% trans 'Pick a date...' %}">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary btn-sm mb-2 mr-sm-2">{% trans "Go to date" %}</button>
                        </div>
                    </div>
                    {% if nb_not_read > 0 %}
                        <button form="mark_all_read_form" type="submit" class="btn btn-primary btn-sm mb-2 mr-sm-2">
                            <i class="fas fa-check-square"></i> {% trans "Mark all as read" %}
                        </button>
                    {% endif %}
                    {% if hidden_operations|length > 0 %}
                        <button id="show-all-operations" type="button" class="btn btn-secondary btn-sm mb-2">
                            <i class="fas fa-eye-slash"></i> {% trans "Show all operations" %}
                        </button>
                    {% endif %}
                </form>
            </div>
        </div>

        {% include "operations/_list.html" with operations=object_list hashtag="tab_tables" %}
    </div>
</div>

{% include "operations/_modal_select_dest_account.html" %}

money/templates/accounts/add.html
{% extends "base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block breadcumb %}
{{ block.super }}

<li class="breadcrumb-item"><a href="{% url 'accounts_index' %}">{% trans "Accounts" %}</a></li>
<li class="breadcrumb-item active">{% trans "Add an account" %}</li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm">
        <h1>{% trans "Add an account" %}</h1>
    </div>
</div>

{% crispy form %}

{% endblock %}

{% block scripts %}
{{ block.super }}
<script>
$(function () {
    $('#id_no_pendings').on('change', function(e) {
        $('#div_id_csvOperations').toggle(!$(this).is(":checked"));
    });
});
</script>
{% endblock %}

money/templates/accounts/detail.html
{% extends "base.html" %}

{% load i18n %}
{% load display_amount %}
{% load account_occupancy %}

{% block breadcumb %}
{{ block.super }}

<li class="breadcrumb-item"><a href="{% url 'accounts_index' %}">{% trans "Accounts" %}</a></li>
<li class="breadcrumb-item active">{{ account.title }}</li>
{% endblock %}

{% block content %}


<div class="row justify-content-between align-items-center">
    <div class="col-auto mr-auto">
        <h1>{{ account.title }}</h1>
    </div>
    <div class="col-auto">
        {% if not account.no_pendings %}
            {% if account.operationtemplate_set.count == 0 %}
                <a class="btn btn-primary btn-sm" href="{% url "operations_add" account.id %}"><i class="fas fa-plus-square"></i> {% trans "Add an operation" %}</a>
            {% else %}
                <div class="btn-group">
                    <a class="btn btn-primary btn-sm" href="{% url "operations_add" account.id %}"><i class="fas fa-plus-square"></i> {% trans "Add an operation" %}</a>
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    <div class="dropdown-menu">
                        {% for ot in account.operationtemplate_set.all %}
                            <a class="dropdown-item" href="{% url "operations_add" account.id %}?template={{ ot.pk }}">{{ ot.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
        <a class="btn btn-primary btn-sm" href="{% url "operations_search" %}?account={{ account.id }}"><i class="fas fa-search"></i> {% trans "Search in this account" %}</a>
        <a class="btn btn-primary btn-sm" href="{% url "accounts_to_csv" account.id %}"><i class="fa fa-file-csv"></i> {% trans "Export to CSV" %}</a>
        <a class="btn btn-warning btn-sm" href="{% url "accounts_edit" account.id %}" title="{% trans 'Edit' %}">
            <i class="fa fa-pen"></i>
        </a>
    </div>
</div>

<hr>

<ul class="nav nav-tabs" id="details-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="home-tab" href="#home" data-toggle="tab" role="tab" aria-controls="home" aria-selected="true">
            <i class="fa fa-certificate"></i> {% trans 'Overview' %}
        </a>
    <li>
    <li class="nav-item">
        <a class="nav-link" id="tables-tab" href="#tables" data-toggle="tab" role="tab" aria-controls="tables" aria-selected="false">
            <i class="fa fa-table"></i> {% trans 'Tables' %}
        </a>
    <li>
    <li class="nav-item">
        <a class="nav-link" id="graphs-tab" href="{% url 'accounts_graph' account.id %}">
            <i class="fa fa-chart-line"></i> {% trans 'Graphs' %}
        </a>
    <li>
    <li class="nav-item">
        <a class="nav-link" id="stats-tab" href="{% url 'accounts_stats' account.id %}">
            <i class="fas fa-percentage"></i> {% trans 'Statistics' %}
        </a>
    <li>
</ul>

<div class="tab-content" id="details-tabContent">
    <div class="tab-pane show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <br>
        <div class="row justify-content-md-center tab-pane show active">
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <dl class="row">
                            {% if not account.no_pendings %}
                            <dt class="col-sm-6">
                                Local balance
                                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Including pending operations"></i>:
                            </dt>
                            <dd class="col-sm-6 text-right">{% display_amount local_balance_with_pending %}</dd>

                            <dt class="col-sm-8">Pending operation amount:</dt>
                            <dd class="col-sm-4 text-right">{% display_amount pending_balance %}</dd>
                            {% endif %}

                            <dt class="col-sm-6">Local bank balance:</dt>
                            <dd class="col-sm-6 text-right">
                                {% if local_balance_without_pending is not None %}
                                    {% display_amount local_balance_without_pending %}
                                {% else %}
                                    -
                                {% endif %}
                            </dd>

                            {% if account.support_amount %}
                            <dt class="col-sm-8">Initial support amount:</dt>
                            <dd class="col-sm-4 text-right">{% display_amount account.support_amount %}</dd>

                            <dt class="col-sm-8">Already taken from the support amount:</dt>
                            <dd class="col-sm-4 text-right">{% display_amount total_from_support_amount %}</dd>

                            <dt class="col-sm-8">Current support amount:</dt>
                            <dd class="col-sm-4 text-right">{% display_amount current_support_amount %}</dd>
                            {% endif %}

                            <dt class="col-sm-6">Bank Balance:</dt>
                            <dd class="col-sm-6 text-right">
                                {% if account.balance is not None %}
                                    {% display_amount account.balance %}
                                    {% if not account.bank_local_balances_can_be_different and account.balance != local_balance_without_pending %}
                                    <i class="fa fa-exclamation-circle text-danger" data-toggle="tooltip" data-placement="top" data-html="true" title="Bank balance and local bank balance don't match: there is a difference of {% display_amount diff_bank_local_balance without_color=True %}"></i>
                                    {% endif %}
                                {% else %}
                                    -
                                {% endif %}
                            </dd>

                            <dt class="col-sm-6">Last update:</dt>
                            <dd class="col-sm-6 text-right">{% if account.balance_date is not None %}{{ account.balance_date|date:"d/m/Y" }}{% else %}-{% endif %}</dd>

                            {% if account.balance_limit is not None %}
                            <dt class="col-sm-6">{% trans "Balance limit" %}:</dt>
                            <dd class="col-sm-6 text-right">
                                {% display_amount account.balance_limit without_color=True %}
                                {% if account.balance_limit is not None %}
                                <br>
                                {% account_occupancy account %}
                                {% endif %}
                            </dd>
                            {% endif %}
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <h2>{% trans "Details" %}</h2>

                <p>
                    <b>{% trans "Title" %}:</b> {{ account.title }}<br>
                    <b>{% trans "Number" %}:</b> {{ account.number }}
                    {% if account.initial_amount != 0 %}
                    <br>
                    <b>{% trans "Initial amount" %}:</b> {% display_amount account.initial_amount %}
                    {% endif %}
                </p>


                {% if account.comment|length != 0 %}
                <h2>{% trans "Notes" %}</h2>

                <p>
                    {{ account.comment|linebreaksbr }}
                </p>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="tab-pane" id="tables" role="tabpanel" aria-labelledby="tables-tab">
        <br>
        {% include "accounts/_tables.html" %}
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ block.super }}
<script>
$(function () {
    $("#show-all-operations").click(function() {
        $(".hidden-operation").each(function() {
            $(this).hide();
            $(this).next().show();
        });

        $(this).hide();
    });

    $(".hidden-operation").each(function() {
        $(this).next().hide();

        $(this).find('.show-operation-btn').first().click(function() {
            var row = $(this).parent().parent();
            row.hide();
            row.next().show();
        });
    });

    $("#show-pending-operations-btn").click(function() {
        $(this).parent().parent().hide();
        $(".hidden-pending-operation").removeClass('d-none');
    });
});
</script>
{% endblock %}

money/templates/accounts/edit.html
{% extends "base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block breadcumb %}
{{ block.super }}

<li class="breadcrumb-item"><a href="{% url 'accounts_index' %}">{% trans "Accounts" %}</a></li>
<li class="breadcrumb-item"><a href="{% url 'accounts_view' account.id %}">{{ account.title }}</a></li>
<li class="breadcrumb-item active">{% trans "Edit" %}</li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm">
        <h1>{% trans "Edit an account" %}</h1>
    </div>
</div>


{% crispy form %}

{% endblock %}